apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: k69r1z8qy-nodejs 
  janus-idp.io/tekton: k69r1z8qy-nodejs
  backstage.io/kubernetes-id: k69r1z8qy-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k69r1z8qy-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml